### ISSUE TITLE
Publish on jsDelivr

### ISSUE THREAD

**Issue by passcod** [maciej-gurban/responsive-bootstrap-toolkit#13]
It would be really cool if this was available on www.jsdelivr.com so I could include it in my CDN'd library bundle (using the [super-useful jsdelivr /g/ feature](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request)).

**Comment by maciej-gurban** [comment]
Hi,

I'm not sure if I'll find time to do that anytime soon, but if you need to load RBT from a CDN, you could use RawGit, and in your project, load the library from:
 `https://rawgit.com/maciej-gurban/responsive-bootstrap-toolkit/master/js/bootstrap-toolkit.min.js`

**Comment by passcod** [comment]
Thanks, that's useful to know, but in that case I'll probably just use a local version. The real advantage of jsDelivr for me is the `/g/` feature mentioned above, which lets me bundle all my CDN'd libraries in one request.
