### ISSUE TITLE
Broken Codepen

### ISSUE THREAD

**Issue by pixelbacon** [maciej-gurban/responsive-bootstrap-toolkit#15]
Codepen tries to pull from `https://rawgit.com/maciej-gurban/responsive-bootstrap-toolkit/master/js/bootstrap-toolkit.min.js` which 404s.

**Comment by pixelbacon** [comment]
Correct link:
`https://rawgit.com/maciej-gurban/responsive-bootstrap-toolkit/master/dist/bootstrap-toolkit.min.js`

**Comment by pixelbacon** [comment]
[Fixed](http://codepen.io/anon/pen/vOKEyR)

**Comment by maciej-gurban** [comment]
Hi Michael,

Thanks for reporting the issue! I forgot to update CodePen example after the directory name changed. It should be working fine now.
