### ISSUE TITLE
Not compatible with Bootstrap 3.3.4

### ISSUE THREAD

**Issue by pixelbacon** [maciej-gurban/responsive-bootstrap-toolkit#17]
[Codepen](http://codepen.io/anon/pen/YXWPNe)

**Comment by maciej-gurban** [comment]
The problem with example on CodePen was, that it included the old way of sniffing window resize events. It changed from being `$(window).bind('resize', fn)` in 2.4.2, to `$(window).resize(fn)` in 2.5.0. The library should work fine with all 3+ versions of Bootstrap.

Once again, thanks for reporting it!

**Comment by pixelbacon** [comment]
My pleasure :)

The code has a good intention so by all means my pleasure.
