### ISSUE TITLE
Folder with compiled js changed its name

### ISSUE THREAD

**Issue by lukaszczernal** [maciej-gurban/responsive-bootstrap-toolkit#18]
Folder with compiled JS files changed its name therefore my project failed unexpectedly when bower has been updated. 

Are you planning to add your project officially to Bower so we can better control our dependencies?

**Comment by maciej-gurban** [comment]
Hi,

It's been added. You can pull it in with:
`bower install responsive-toolkit`

It's true the directory name change hasn't been communicated properly, and for that, my apologies. Hopefully now that the project is in Bower, such problems will not arise again.

**Comment by lukaszczernal** [comment]
Thanks for quick reply. Thats great info.
