### ISSUE TITLE
Change detection element from class to id

### ISSUE THREAD

**Issue by migig** [maciej-gurban/responsive-bootstrap-toolkit#21]
The injected `<div class="responsive-bootstrap-toolkit"></div>` would be found faster if it used an `id` rather than a `class`.

Unless it's cached, but I couldn't figure out from the code if it does that.

**Comment by maciej-gurban** [comment]
While that's true that IDs tend to be a little bit faster than classes, this div is injected into the document only once, at the initialization of the script. Performance improvement of using IDs over classes would be unnoticeable in this case.

**Comment by migig** [comment]
No what I meant is not that it's slow during injection, but rather slow when querying.

For such an obvios perf gain, it makes sense to use an ID, especially since it's backwards compatible (won't break anything as the library handles all that stuff internally).

**Comment by maciej-gurban** [comment]
The way this library works is that it creates jQuery objects from given syntax (visibility divs), and stores these objects internally, as a property (self.breakpoints). These divs are them injected into DOM and jQuery stores a reference to them.

Therefore, whenever you use any of the methods, they do not query the DOM again, but rather use the reference to a DOM node that has been created upon injection, and return a value from (whether the div is visible or not) of that DOM node.

So what I'm saying is, the 'caching' you mention in the last paragraph is what is happening here.

**Comment by migig** [comment]
@maciej-gurban Great! :beer:
