### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by robertsearle** [maciej-gurban/responsive-bootstrap-toolkit#23]
npm ERR! 404 'bootstrap-toolkit' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it

**Comment by glamic-ep** [comment]
Yes, please, I would like to bug the author too. :)

**Comment by rogovdm** [comment]
+1

**Comment by rogovdm** [comment]
@maciej-gurban ping

**Comment by timtips** [comment]
would also love to have it available as a npm dep :) thx for sharing

**Comment by maciej-gurban** [comment]
Sorry it's taking so long; I've been exceptionally busy as of recent. I won't promise any specific dates, but I hope to get this out soon.

**Comment by maciej-gurban** [comment]
NPM support has been added.

See: [Release 2.6.0](https://github.com/maciej-gurban/responsive-bootstrap-toolkit/releases/tag/2.6.0)
