### ISSUE TITLE
Version mismatch - wrong version installed by bower

### ISSUE THREAD

**Issue by krzysieki** [maciej-gurban/responsive-bootstrap-toolkit#27]
Hi 

First, thanks for your work!

I have some problems with installing latest version using bower.

bower install ...

installs version tagged with "2.5.0" which lacks "dist" folder and some version inconsistencies are present in files .bower.json, bower,json, changelog (2.2, 2.4.1, 2.5 ??).

I suppose "bower install" should install tag "v2.5.0"

**Comment by uiureo** [comment]
I ran into this issue too.

**Comment by lukaszczernal** [comment]
+1 Count me in. I need to refer to commit id to get the latest version.

**Comment by tomasz-scislo-xstream** [comment]
+1

**Comment by cdmckay** [comment]
Just wasted an hour on this. You can workaround it by doing:

`bower install response-toolkit#9a74131fa53c1e009943a7aca5e91620b3dc306b`

I think the issue is @maciej-gurban is using 2.5.0 and v2.5.0 for the same package so Bower is serving the wrong package?

**Comment by maciej-gurban** [comment]
Sorry for the inconvenience. I'm not sure myself how that duplicate 2.5.0 tag appeared. I corrected the tags; running bower install responsive-toolkit should pull in the correct version now. I'll create 2.5.1 version soon with all the docs changes (since 2.5.0 is not still a little behind master).

Thanks for the pointer about two different tags @cdmckay - I wasn't aware of that double tag issue at all.

**Comment by cdmckay** [comment]
Awesome, thanks @maciej-gurban

**Comment by cdmckay** [comment]
@maciej-gurban why is this closed? It's still downloading the wrong version on Bower

**Comment by maciej-gurban** [comment]
I tested on a clear project (where the library wasn't installed at all) on two different machines, and the correct version got downloaded. You can try either of these options:
- Remove `responsive-toolkit` directory from `bower_components`, edit your `bower.json` and lock the version to be `"responsive-toolkit": "2.5.0"`. Then execute `bower install`
- Remove `responsive-toolkit` directory from `bower_components`, remove it from your `bower.json`. Then execute `bower install responsive-toolkit --save-dev`
- Run `bower cache clean` and `bower install`
