### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by meydjer** [maciej-gurban/responsive-bootstrap-toolkit#39]
`Uncaught ReferenceError: module is not defined`

Downgraded to v2.6.0 and the error is gone.

**Comment by maciej-gurban** [comment]
Can you share some more details? You were using 2.6.1 I guess. Which file exactly threw this and in what environment?

**Comment by maciej-gurban** [comment]
Found and fixed the problem. Thank you for reporting the issue! Please upgrade your version to 2.6.3.

**Comment by Z33** [comment]
Any chance we can get 2.6.3 on npm? It's currently limited to 2.6.1 and I'm having the same issue.
