### ISSUE TITLE
Can't find variable: module

### ISSUE THREAD

**Issue by silentFred** [maciej-gurban/responsive-bootstrap-toolkit#41]
Hi there,

I noticed the latest version breaks in Karma using PhantomJS. It's this little bit here that causes it. It looks pretty safe to me so not sure why Karma is complaining. Any ideas?

``` javascript
if (module && module.exports) {
    module.exports = ResponsiveBootstrapToolkit;
}
```

**Comment by maciej-gurban** [comment]
Hi Frederick,

That's what I thought initially as well, but the correct check should be as follows:

```
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ResponsiveBootstrapToolkit;
}
```

This has been pushed as a hotfix awhile ago, and it should be enough that you update the toolkit to version 2.6.3.

**Comment by silentFred** [comment]
Nice!

Sorry about that. I just pulled latest major :)
