### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by silentFred** [maciej-gurban/responsive-bootstrap-toolkit#43]
In case someone needed the bootstrap 4 backwards compatible mapping:

`
var visibilityDivs = {
            'xs': $('<div class="hidden-xl-up"></div>'),
            'sm': $('<div class="hidden-lg-up"></div>'),
            'md': $('<div class="hidden-md-up"></div>'),
            'lg': $('<div class="hidden-sm-up"></div>')
        };
`

**Comment by maciej-gurban** [comment]
This is incorrect. Refer to [this snippet](https://github.com/maciej-gurban/responsive-bootstrap-toolkit/blob/bootstrap-4-integration/dist/bootstrap-toolkit.js#L25)

**Comment by silentFred** [comment]
Thank you @maciej-gurban
