### ISSUE TITLE
IE8: Object doesn't support this property or method

### ISSUE THREAD

**Issue by cylkee** [maciej-gurban/responsive-bootstrap-toolkit#44]
IE8 on Win 7 is giving me the following error:

`Object doesn't support this property or method`

And refers to line 105:

`var breakpointList = Object.keys(self.breakpoints);`

I'm using v2.6.3, inserted before `</body>` and before my own JavaScript, and after jquery-1.12.4.min.js

I couldn't find in the readme anything about browser support.  Is IE8 supported?

**Comment by maciej-gurban** [comment]
Hi cylkee. There's no support for IEs lower than 9, but what you could do is use a polyfill. One of them can be found [here](https://gist.github.com/jonfalcon/4715325).

**Comment by cylkee** [comment]
Thanks.
