### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by BenjaminHoegh** [maciej-gurban/responsive-bootstrap-toolkit#46]
Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by maciej-gurban** [comment]
Are you sure?
`http://jsonlint.com/`: `Valid JSON`.

**Comment by BenjaminHoegh** [comment]
That was what it say, and I try multiple times

**Comment by maciej-gurban** [comment]
What exactly did you use to parse the package.json? What outputs that error?

**Comment by BenjaminHoegh** [comment]
npm install responsive-toolkit
