### ISSUE TITLE
npm version outdated / no boostrap4 support

### ISSUE THREAD

**Issue by kristian** [maciej-gurban/responsive-bootstrap-toolkit#49]
Hello, I really like the project and I would like to use it in a boostrap4 project. Unfortunately the npm version does not support boostrap4 yet (as the boostrap4-integration branch wasn't merged to master yet, I guess). Could you explain why you are holding it back? Adding the `detectionDivs` for boostrap4 shouldn't cause any negative side effects for the master branch, right? Thanks!

**Comment by maciej-gurban** [comment]
Only due to lack of time. You can still use it with v4, just provide custom visibility divs on your own

**Comment by kristian** [comment]
@maciej-gurban Thanks, will do so. As boostrap v4 will get out of the alpha status soon, an update would be highly appreciated in any case! 👍 Thanks again!

**Comment by maciej-gurban** [comment]
I think I also had the "v4 must be coming soon" hopes when merging this PR: #35 a year ago ;) Anyhow, as soon as RC lands, I'll add v4 support.
