### ISSUE TITLE
What is the major difference between 1.5 and 2.3

### ISSUE THREAD

**Issue by lustremedia** [maciej-gurban/responsive-bootstrap-toolkit#5]
Could you explain the difference between the versions? Is 2.3 compatible with 1.5? Can I just exchange the libs or would I have to do more work?
Maybe you could elaborate on that in the docs ...

Thanks for the great script!

**Comment by lustremedia** [comment]
I can already tell that the breakpoints from 1.5 can be taken out of the dom since they are appended to the body in 2.3

**Comment by maciej-gurban** [comment]
Hi, have you read the [changelog](https://github.com/maciej-gurban/responsive-bootstrap-toolkit/blob/master/CHANGELOG.md)? It explains the changes in each version.

**Comment by lustremedia** [comment]
Ah my vision was blurred, sorry. Ok that explains everything! Maybe linking that with the readme would be helpful.

**Comment by maciej-gurban** [comment]
Good call. Will do that.

**Comment by maciej-gurban** [comment]
Updated: 5006b7f4f2f6bda6ff7fea1a01ddd91d4ab41dfe
