### ISSUE TITLE
Usage in VueJS2 single-file-components leads to error

### ISSUE THREAD

**Issue by rivieiraa** [maciej-gurban/responsive-bootstrap-toolkit#50]
I'm trying to import responsive-toolkit into my VueJS .vue component script like that:
`import jQuery from 'jquery'`
`import ResponsiveToolkit from 'responsive-toolkit'`

and i'm geting an error: 'caught ReferenceError: jQuery is not defined'

here's code spot where i get it: http://take.ms/8myFR

In case it's important, im using gulpjs + browserify [transforms: babelify, vueify, envify, aliasify]  to bundle and tansform my JS

Correct me if i'm doing something wrong, but all libs i included before in the same style work fine. slick-carousel for example.

**Comment by maciej-gurban** [comment]
It might be because RBT looks for jQuery in `window`, so to make it work you would need to do:
```
import jQuery from 'jquery'
window.$ = jQuery;
import ResponsiveToolkit from 'responsive-toolkit'
```

You might also get away by defining `const $ = jQuery` in the file in which you're using RBT, but I haven't tested that case.

**Comment by rivieiraa** [comment]
Declaring const $ or const jQuery does nothing when you bundle your JS using browserify or other tools, so injecting jQuery as dependency is a good solution IMHO.

#51 Suggested pull request.
