### ISSUE TITLE
Manually initialize toolkit from Angular 6 app - advice needed

### ISSUE THREAD

**Issue by silentFred** [maciej-gurban/responsive-bootstrap-toolkit#54]
Hi all,

Just wondering if anyone knows hoe one can manually initialize the toolkit's inner mechanisms to add the custom detection divs to the DOM etc?

I'm working on an Angular 6 app and struggling to make sure custom breakpoints take effect before I initialize some state in my application.

Kind regards,
Fred

**Comment by maciej-gurban** [comment]
Sorry for late reply; you probably found the solution already. I think the solution would be to simply run the initialization before your app bootstraps, i.e. initialize the lib inside a file imported before main app file that initializes angular. If that's not possible, you could add a `<script>` tag before any other app-related script tags, and initialize there.
