### ISSUE TITLE
Is there a reason why main.js in bower is ignored

### ISSUE THREAD

**Issue by lustremedia** [maciej-gurban/responsive-bootstrap-toolkit#6]
Just pulled the repo via bower and saw that main.js is not included.

However main.js would be helpful to get started ...

**Comment by maciej-gurban** [comment]
Good point. Following the example of other projects, I'd consider adding README.md to the files pulled in by bower.

**Comment by maciej-gurban** [comment]
README.md now contains all information necessary to start using the library.

5006b7f4f2f6bda6ff7fea1a01ddd91d4ab41dfe

**Comment by lustremedia** [comment]
Cool thanks @maciej-gurban
