### ISSUE TITLE
Enhance breakpoint matching functionality

### ISSUE THREAD

**Issue by hubsmoke** [maciej-gurban/responsive-bootstrap-toolkit#7]
Thanks for the tool

I just wanted to note that it'd be nice to allow multiple arguments to viewport.is such as `viewport.is('sm', 'xs')`

and/or have unary comparison operators like `viewport.is('<=sm')` and `viewport.is('>sm')`

**Comment by maciej-gurban** [comment]
How about:

    switch( viewport.current() ) {
        case 'xs':
        case 'sm': // fall through
            // Code
        break;
    }

**Comment by lustremedia** [comment]
+1

**Comment by mikelieser** [comment]
+1

**Comment by maciej-gurban** [comment]
Requested feature, in the form of parsable unary operators, currently available in in Enhanced-breakpoint-matching feature branch at ef803c40462d3671e296ac07e49fe05c1de9d154. 

Comments very welcome.

**Comment by maciej-gurban** [comment]
Functionalities merged into master branch.
